<?php
/**

Copyright 2016 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-a532ba
Date:    2016-02-09 21:05:23
Version: v1.0-rc13
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

namespace JF;

class Config {

    public static function getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-a532ba",
    "email": {
        "to": "john@trilogymentors.com",
        "cc": "",
        "bcc": "",
        "subject": "{c37}",
        "template": "",
        "fromName": "{c1}"
    },
    "admin": {
        "users": "admin:17766",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "yellow"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
        {
            "label": "Your Name",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": ""
                }
            },
            "cid": "c1"
        },
        {
            "label": "Child's Name",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c98"
        },
        {
            "label": "Phone",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c67"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                }
            },
            "cid": "c2"
        },
        {
            "label": "Select a Trilogy Mentor Type",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Academics",
                        "checked": false
                    },
                    {
                        "label": "Athletics",
                        "checked": false
                    },
                    {
                        "label": "Arts",
                        "checked": false
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "dependOn": {
                    "enabled": false,
                    "remote": false
                }
            },
            "cid": "c37"
        },
        {
            "label": "Choose an Academic Category",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Math",
                        "checked": false
                    },
                    {
                        "label": "English",
                        "checked": false
                    },
                    {
                        "label": "Basic English",
                        "checked": false
                    },
                    {
                        "label": "Biology",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Physics",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Calculus",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Public Speaking",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Accounting 101",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Econ 101",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Finance 101",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Marketing 101",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Philosophy",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Psychology",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false,
                "dependOn": {
                    "enabled": false,
                    "cid": "c48"
                }
            },
            "cid": "c43"
        },
        {
            "label": "Choose an Athletics Category",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Soccer",
                        "checked": false
                    },
                    {
                        "label": "Baseball",
                        "checked": false
                    },
                    {
                        "label": "Basketball",
                        "checked": false
                    },
                    {
                        "label": "Field Hockey",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Men's & Women's Lax",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Football",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Swimming",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Ruby",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Quidditch",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false,
                "dependOn": {
                    "enabled": false
                }
            },
            "cid": "c48"
        },
        {
            "label": "Choose an Arts Category",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "Piano",
                        "checked": false
                    },
                    {
                        "label": "Violin",
                        "checked": false
                    },
                    {
                        "label": "Music Composition",
                        "checked": false
                    },
                    {
                        "label": "Drums",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Guitar",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Trumpet",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Flute",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Saxophone",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Ukulele",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "Cello",
                        "value": null,
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c62"
        },
        {
            "label": "What day do you need your Trilogy Mentor?",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "fa fa-calendar",
                    "rightText": ""
                },
                "date": {
                    "startView": "0",
                    "minViewMode": "0",
                    "multidate": "false",
                    "weekStart": "1"
                }
            },
            "cid": "c75"
        },
        {
            "label": "Trilogy Mentor Packages and Prices",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false,
                    "responsive": true
                },
                "mainDescription": "",
                "description": "1 Hour of Academic Tutoring - $35.00\n4 Hours of Academic Tutoring - $34.50\n8 Hours of Academic Tutoring - $34.00\n12 Hours of Academic Tutoring - $33.00\n\n1 Hour of Athletics\/Arts Tutoring - $40.00\n4 Hours of Athletics\/Arts Tutoring - $39.00\n8 Hours of Athletics\/Arts Tutoring - $38.00\n12 Hours of Athletics\/Arts Tutoring - $37.00"
            },
            "cid": "c81"
        },
        {
            "label": "Select a Trilogy Mentor Tutoring Package",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- Select -",
                        "value": "#novalue",
                        "checked": false
                    },
                    {
                        "label": "1 Hour of Academic Tutoring",
                        "checked": false,
                        "value": ""
                    },
                    {
                        "label": "4 Hours of Academic Tutoring",
                        "checked": false
                    },
                    {
                        "label": "8 Hours of Academic Tutoring",
                        "checked": false
                    },
                    {
                        "label": "12 Hours of Academic Tutoring",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "#novalue",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "1 Hour of Athletic\/Arts Tutoring",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "4 Hours of Athletic\/Arts Tutoring",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "8 Hours of Athletic\/Arts Tutoring",
                        "value": null,
                        "checked": null
                    },
                    {
                        "label": "12 Hours of Athletic\/Arts Tutoring",
                        "value": null,
                        "checked": false
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "presetJson": "",
                "multiple": false,
                "dependOn": {
                    "enabled": false,
                    "cid": "c43",
                    "remote": false
                }
            },
            "cid": "c80"
        },
        {
            "label": "Untitled",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "cid": "c65",
            "labelHide": true
        },
        {
            "label": "Untitled",
            "field_type": "creditcard",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "subfields": {
                "ccNumber": {
                    "order": 1,
                    "label": "Card number",
                    "field_options": {
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Invalid credit card number"
                            }
                        }
                    },
                    "cid": "ccNumber"
                },
                "ccFullname": {
                    "order": 2,
                    "label": "Name on card",
                    "field_options": {
                        "validators": {
                            "required": {
                                "enabled": false
                            }
                        }
                    },
                    "cid": "ccFullname"
                },
                "ccExpiryDate": {
                    "order": 3,
                    "label": "Expiration date",
                    "field_options": {
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Invalid expiration date"
                            }
                        }
                    },
                    "cid": "ccExpiryDate"
                },
                "ccCVC": {
                    "order": 4,
                    "label": "Card CVC",
                    "field_options": {
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "Invalid CVC code"
                            }
                        }
                    },
                    "cid": "ccCVC"
                }
            },
            "cid": "c110"
        },
        {
            "label": "Checkboxes",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "I agree to Trilogy Mentor's Terms and Conditions and Privacy Policy, and that the entered information is accurate and complete.",
                        "checked": false
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)"
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)"
                    }
                },
                "presetJson": ""
            },
            "cid": "c105"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "cid": "c100"
        }
    ]
}
<?php /**JSON_END**/

	    $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

} // end of Config class